# Use the official Node.js image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the package files to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port on which the application will run
EXPOSE 5000

# Run the application
CMD ["npm", "start"]
